# filename: main.py

import matplotlib.pyplot as plt
import copy
import random
from io import BytesIO
from fastapi import FastAPI, responses
from pydantic import BaseModel, Field
from typing import List, Optional

from packutils.visual.packing_visualization import PackingVisualization
from packutils.data.bin import Bin

import matplotlib
matplotlib.use('Agg')

app = FastAPI()


@app.get("/")
async def status():
    return {"status": "Healthy"}


@app.get(
    "/bin",

    # Set what the media type will be in the autogenerated OpenAPI specification.
    # fastapi.tiangolo.com/advanced/additional-responses/#additional-media-types-for-the-main-response
    responses={
        200: {
            "content": {"image/png": {}}
        }
    },

    # Prevent FastAPI from adding "application/json" as an additional
    # response media type in the autogenerated OpenAPI specification.
    # https://github.com/tiangolo/fastapi/issues/3258
    response_class=responses.Response
)
def get_bin_image():
    vis = PackingVisualization()

    bin = Bin(10, 1, 10)

    image = vis.visualize_bin(bin, show=False, return_png=False)

    # convert the image into bytes
    buffer = BytesIO()
    image.savefig(buffer, format='png')
    plt.close()
    buffer.seek(0)

    return responses.StreamingResponse(buffer, media_type="image/png")
